packages:
  - .
enableGlobalVirtualStore: true # does not work with vite
minimumReleaseAge: 4320 # 72 hours
nodeVersion: '24.13.1'
engineStrict: true
savePrefix: ''
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
